# Generated by Django 4.2.10 on 2024-02-22 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_availability', to='user_profiles.address'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_offers_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
