# Generated by Django 4.2.10 on 2024-02-23 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employer',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_logos/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
